name: Manually Add Code References to LaunchDarkly Project

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'User alias or LD env key'
        required: true

env:
  LD_PROJECT_KEY: ${{ github.event.inputs.name }}-ld-demo
  LD_API_KEY: ${{ secrets.LD_EAP_API_KEY }}

jobs:
  add-code-references:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 11
          
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.12.0
        with:
          accessToken: ${{ env.LD_API_KEY }}
          projKey: ${{ env.LD_PROJECT_KEY }}
          repoName: main
